### ISSUE TITLE
Replace `admin:admin` default credentials

### ISSUE THREAD

**Issue by setiah** [opensearch-project/security#1576]
**Is your feature request related to a problem? Please describe.**
The default `admin:admin` credential is too weak and a sure-fire way to get hacked. Though the documentation recommends users to change the default passwords, it can be easily missed. Such weak defaults can be very easily exploited and lead to massive data leaks (remember [Equifax attack](https://www.forbes.com/sites/kateoflahertyuk/2019/10/20/equifax-lawsuit-reveals-terrible-security-practices-at-time-of-2017-breach/?sh=446983d93d38)?). 

The second gap is, in the existing distribution, there's no default password policy to ensure stronger passwords. It needs to be configured explicitly by users. That is why such weak credentials are able to slip through the cracks.

**Describe the solution you'd like**
Remove the default passwords provided in `internal_users.yml`. Instead, have the `admin` user setup passwords for internal users once the OpenSearch process is up. These passwords can be set up post-installation using a REST API and `admin` certificates (for authentication). Setting password for `admin` user would look something like -
```
PATCH _opendistro/_security/api/internalusers/admin --key admin-key.pem --cert admin.pem --cacert root-ca.pem -d'
{
    "password": "quCn52_8\*N8"
}
'
```
To make this further easy, OpenSearch distribution could provide a tool such as an OpenSearch shell client to make it easy for admin user to configure all users. This shell client could also help with autogenerating strong passwords and can be further extended to support for more administrative functions in future. 
 
In addition to this, we should also add a default password policy to only allow passwords that match a certain strength criteria. Obv, these policies are overridable depending on the user/enterprise needs. Having a strong default policy will protect against insecure password configurations.

**Describe alternatives you've considered**

**Additional context**
This is related to https://github.com/opensearch-project/OpenSearch/issues/1618

**Task breakdown**
- [x] Remove default passwords for inbuilt users in internal_users.yml, deprecate now and remove password field from yml in 2.0
- [x] Configure strong default password policy and also make it overridable via yml.
- [x] Write tool for password setup (to be used by admin).
- [x] Add auto-password-generation logic to the tool to ease user experience during setup.
- [ ] #1787

**Comment by CEHENKLE** [comment]
@PhilipMay Agree.  Take a look at:  https://github.com/opensearch-project/OpenSearch/issues/1029 We plan to make changes this year in a major version, but let's not wait if there are low things we can do before that.

**Comment by peternied** [comment]
There was a related issue filed https://github.com/opensearch-project/security-dashboards-plugin/issues/1008 where the admin password was not able to be updated in the UX

**Comment by zalseryani** [comment]
Any update on this case !!

**Comment by kingnarmer** [comment]
Checking if there is update on this issue ?

**Comment by zalseryani** [comment]
The only way to solve this issue is to add your internal_users.yml under ```securityConfig.config.data.config.yml``` configuration section in your helm chart. 

EX: 
```yaml
      internal_users.yml: |-
        ---
        _meta:
          type: "internalusers"
          config_version: 2

        admin:
          hash: ""
          reserved: true
          backend_roles:
          - "admin"
```
- Use the help of this website to bycrypt hash your password [Online Bcrypt Hash Generator](https://www.devglan.com/online-tools/bcrypt-hash-generator)

**Comment by dblock** [comment]
I wrote up https://code.dblock.org/2023/08/08/changing-the-default-admin-password-in-opensearch.html which should show how hard this is to actually do today.

**Comment by decyphertek-io** [comment]
It appears that setting admin user and kibanaserver as read only in the internal_users.yml ( reserved: true ) , prevents removing these insecure accounts via security>Internal users, this is more than likely by design , so that the average user gets frustrated trying to use the securityadmin.sh script and just buys the product through AWS. The issue with the securityadmin.sh script is that it doesnt just allow pushing changes to the internal_users.yml , you have to also add certs. I was excited about OpenSearch being open source, when I see tactics like this, makes me question why? I ask, what is easier, for the reserved:true to be removed from admin and kibanaserver users in the internal_users.yml on the next release , removing all the demo users and allowing people to choose which users they want easily, or continue using this script? ( Super easy to understand right, since it clearly shows all the right directories ../right/..../or/.../wrong/ . Its been over two years and this issue still exists. 

./securityadmin.sh -f ../../../config/opensearch-security/internal_users.yml \
  -t internalusers \
  -icl \
  -nhnv \
  -cacert ../../../config/root-ca.pem \
  -cert ../../../config/kirk.pem \
  -key ../../../config/kirk-key.pem

**Comment by decyphertek-io** [comment]
Here is the quick answer on Debian systems, using the existing certs, and changing the internal_users.yml . If you want to generate your won self signed certs or import your own. https://opensearch.org/docs/latest/security/configuration/generate-certificates/

    sudo /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -p <password> 
    sudo vim /etc/opensearch/opensearch-security/internal_users.yml 
    sudo /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -f /etc/opensearch/opensearch- 
    security/internal_users.yml -t internalusers  -icl -nhnv -cacert /etc/opensearch/root-ca.pem -cert /etc/opensearch/kirk.pem - 
    key /etc/opensearch/kirk-key.pem

**Comment by decyphertek-io** [comment]
Debian/Ubuntu Solution:
--------------------------------

   # Install Opensearch
   sudo apt update && sudo apt upgrade -y
   sudo apt-get update && sudo apt-get -y install lsb-release ca-certificates curl gnupg2
   # This command appears in two lines, make sure to include them in one.
   curl -o- https://artifacts.opensearch.org/publickeys/opensearch.pgp | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings 
   /opensearch-keyring
   # This command appears in two lines, make sure they are one. 
   echo "deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch  
   /2.x/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-2.x.list
   sudo apt update && sudo apt install opensearch -y 
   sudo vim /etc/opensearch/opensearch-security/internal_users.yml
   # change reserved: true to reserved: false

   # Install opensearch-dashboard
   # This command appears in two lines, make sure they are one. 
   curl -o- https://artifacts.opensearch.org/publickeys/opensearch.pgp | sudo gpg --dearmor --batch --yes -o /usr/share/keyrings 
   /opensearch-keyring
   # This command appears in two lines, make sure they are one
   echo "deb [signed-by=/usr/share/keyrings/opensearch-keyring] https://artifacts.opensearch.org/releases/bundle/opensearch- 
   dashboards/2.x/apt stable main" | sudo tee /etc/apt/sources.list.d/opensearch-dashboards-2.x.list
   sudo apt update && sudo apt install opensearch-dashboards -y 
   sudo vim /etc/opensearch-dashboards/opensearch_dashboards.yml
   # uncomment server.port: 5601 
   # uncomment and change server.host: "localhost" to server.host: "0.0.0.0"

   # Opensearch 2.x > Java 17 compatible
   sudo apt install openjdk-17-jdk 
   export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s:bin/java::") 
   export OPENSEARCH_JAVA_HOME=$JAVA_HOME 
   java --version 
   echo $JAVA_HOME  
   echo $OPENSEARCH_JAVA_HOME 

   # Start the daemons
   sudo systemctl daemon-reload
   sudo systemctl enable opensearch
   sudo systemctl start opensearch
   sudo systemctl enable opensearch-dashboards
   sudo systemctl start opensearch-dashboards

   # Login ( Can now manage all users from GUI ) 
   http://ip-of-server:5601
   user: admin
   pass: admin
   manage users > management > security > internal users > delete & change passwords

   # HTTPS options
   * nginx
   * search guard
   * The complicated security script process.

**Comment by peternied** [comment]
@scrawfor99's pull request [1] to address this issue was recently merged in to main.  We are about to backport this change into 2.x and want to get some feedback on how we think about approaching this.

#### Currently Planned Behavior
If a password for the admin account is not supplied, the demo_configuration script will exit early with the following message.

```bash
echo "Unable to find the admin password for the cluster. Please run 'export initialAdminPassword=<your_password>' 
or create a file $ADMIN_PASSWORD_FILE with a single line that contains the password."
```

Otherwise the following will be printed in the middle of the script
```
echo "   ***************************************************"
echo "   ***   ADMIN PASSWORD SET TO: $ADMIN_PASSWORD    ***"
echo "   ***************************************************"
```

What do we think about these changes going into the 2.x release?  Are there any modifications that would make this more palatable?  Note, I'm also going to mark this `untriaged` to make sure it gets discussed during the next triage meeting.

- [1] https://github.com/opensearch-project/security/pull/3329

**Comment by davidlago** [comment]
[Triage] Maintainers agree to take the tradeoff of "breaking" new installs that don't provide a default password for the admin user, for the sake of better securing future cluster installs. This does not break current clusters that get upgraded to a newer version, as those would already have created their admin user/password.

That said, we want to make sure that at the very least we fix the docker images we publish alongside our artifacts (and the functional tests) to account for this change. Until those are addressed, the 2.x backport in #3414 should be blocked.

**Comment by guldil** [comment]
> ## Opensearch admin:admin Debian/Ubuntu Solution:
> 
> ```
>  # Login ( Can now manage all users from GUI ) 
>  http://ip-of-server:5601
>  user: admin
>  pass: admin
>  manage users > management > security > internal users > delete & change passwords

i can't update admin account : {"status":"FORBIDDEN","message":"Resource 'admin' is reserved."}
i can remove all "non reserved" account
i move to this step

>  # (Optional) Opensearch Security Script Method:
>  # Add your chosen password has to the internal users yml.
>  sudo  /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -p <new-password>
> 
>  # Update the Internal users yml
>  sudo vim /etc/opensearch/opensearch-security/internal_users.yml
> 
>  # Dev certs, to generate your own - https://opensearch.org/docs/latest/security/configuration/generate-certificates/
>  # This appears on three lines, except should be one command. 
>  sudo /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -f /etc/opensearch/opensearch-security 
>  /internal_users.yml -t internalusers  -icl -nhnv -cacert /etc/opensearch/root-ca.pem -cert /etc/opensearch/kirk.pem -key 
>  /etc/opensearch/kirk-key.pem
> ```

and it's working admin password is changed and demo account are back gain...

at least I was able to change the default password so thank you :)

**Comment by scrawfor99** [comment]
> > ## Opensearch admin:admin Debian/Ubuntu Solution:
> > ```
> >  # Login ( Can now manage all users from GUI ) 
> >  http://ip-of-server:5601
> >  user: admin
> >  pass: admin
> >  manage users > management > security > internal users > delete & change passwords
> > ```
> 
> i can't update admin account : {"status":"FORBIDDEN","message":"Resource 'admin' is reserved."} i can remove all "non reserved" account i move to this step
> 
> > # (Optional) Opensearch Security Script Method:
> > # Add your chosen password has to the internal users yml.
> > sudo  /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -p 
> > # Update the Internal users yml
> > sudo vim /etc/opensearch/opensearch-security/internal_users.yml
> > # Dev certs, to generate your own - https://opensearch.org/docs/latest/security/configuration/generate-certificates/
> > # This appears on three lines, except should be one command.
> > sudo /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh -f /etc/opensearch/opensearch-security
> > /internal_users.yml -t internalusers  -icl -nhnv -cacert /etc/opensearch/root-ca.pem -cert /etc/opensearch/kirk.pem -key
> > /etc/opensearch/kirk-key.pem
> 
> and it's working admin password is changed and demo account are back gain...
> 
> at least I was able to change the default password so thank you :)

Hey @guldil, I don't think these changes have gone out yet. You should still be able to use the default credentials `admin:admin` for the time being. We will have to wait for the next release to roll out these changes (some of which are still in progress courtesy of @DarshitChanpura ) :)

**Comment by guldil** [comment]
@scrawfor99 but i dont want to use default password, i start a VM with OpenSearch on my private cloud and i can't let the VM with default password, i need remote access on it.

For me it's a good solution, i installed OpenSearch 2.11, i change certificates used by default (root-ca / kirk) with my own certificates issued with my "root-ca-new" and i change admin password with my own "admin" (the default kirk). It helped me understand how this part worked.

**Comment by scrawfor99** [comment]
Hi @guldil, thanks for the clarification. What you described should work--I was just trying to clarify why the steps on this issue may not be operable quite yet. Everything listed on the documentation website should still work for your use case.

**Comment by guldil** [comment]
@scrawfor99 yes i found documentation too late https://opensearch.org/docs/latest/install-and-configure/install-opensearch/debian/#configure-tls, eveything is on it.

Maybe documentation installation of Dashboard could be better https://opensearch.org/docs/latest/install-and-configure/install-dashboards/debian/ and https://opensearch.org/docs/latest/install-and-configure/install-dashboards/tls/ when you change Certificates / CA (like the TLS one of OpenSearch Only)

**Comment by LinTechSo** [comment]
Hi, 
any updates ?

**Comment by kingnarmer** [comment]
I am having same issue . Would be good if this cloud be automated. Ideal situation will be to pass the desired password as input to script or playbook.

**Comment by zalseryani** [comment]
if you are using helm charts for deploying opensearch, you can update your opensearch helm chart to use internal_users.yml template and add your admin user password there, 

for future changes, you can use securityadmin.sh for retrieving the security index data (users, roles, rolesmapping, etc) and put them into a folder and update them and re-uploading them to security index again using securityadmin.sh shell also. 

- retrieve security index information 
```bash
./securityadmin.sh -cd ../../../config/security_backup/ -icl -nhnv \
    -cacert ../../../config/root-ca.pem \
    -cert ../../../config/admin.pem \
    -key ../../../config/admin-key.pem -r
```

- update admin bycrypt hash and reupload using the same script (please make sure to rename all the files again without the timestamp or date in the files naming) 
```bash
./securityadmin.sh -cd ../../../config/security_backup/ -icl -nhnv \
    -cacert ../../../config/root-ca.pem \
    -cert ../../../config/admin.pem \
    -key ../../../config/admin-key.pem
```

Opensearch Version: 2.9.0 -- deployed with helm chart version (opensearch-2.14.0)

# References
- [Applying changes to configuration files](https://opensearch.org/docs/2.11/security/configuration/security-admin/)

**Comment by scrawfor99** [comment]
This is actively being worked on by @derek-ho and @DarshitChanpura they are making great progress and hoping to get this out in 2.12. That being said, we have to wait for 2.12 at the earliest since this marks a fairly large UX/UI change from the current way of doing things. You are welcome to check out some of their work over on the repo's pull request list.

**Comment by peternied** [comment]
@DarshitChanpura Could you link this to the meta issue where we are addressing this?

**Comment by DarshitChanpura** [comment]
The effort replace default admin password with a custom supplied password is being tracked here:
- https://github.com/opensearch-project/security/issues/3622
- https://github.com/opensearch-project/security/issues/3624
- https://github.com/opensearch-project/security/issues/3415

The issues stemmed from this spike: https://github.com/opensearch-project/security/issues/3560

**Comment by DarshitChanpura** [comment]
The default credentials for demo admin user have been replaced with a custom password requirement, and this feature has been shipped in 2.12.0. Marking this issue as complete.

Please feel free to re-open if something was missed.
