### ISSUE TITLE
[Meta] Improved Integration Tests Wave One

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2264]
Within this project there are now two different models for integration tests.  There are tests that reside under `test` [1] and `integrationTest` [2] are based on principles for test setup and verification.  While there are significant contributions of new tests they are not fully online as part of the pull request workflow.  While this is only the begining of this effort I'd like to capture an end state for the first wave of these tests and the items that should be completed.

Infrastructure Tasks
- [ ] In [CI.yml](https://github.com/opensearch-project/security/blob/93fe6337f78a01e8316213b0998562732701511e/.github/workflows/ci.yml#L77) remove `continue-on-error: true` for the integration test workflow
- [x] https://github.com/opensearch-project/security/issues/2184

Outstanding Pull Requests (As of Nov 16th)
- [ ] https://github.com/opensearch-project/security/pull/2155
- [x] https://github.com/opensearch-project/security/pull/2211
- [x] https://github.com/opensearch-project/security/pull/2227
- [x] https://github.com/opensearch-project/security/pull/2245
- [x] https://github.com/opensearch-project/security/pull/2255
- [ ] https://github.com/opensearch-project/security/pull/2258

[1] https://github.com/opensearch-project/security/tree/main/src/test
[2] https://github.com/opensearch-project/security/tree/main/src/integrationTest

**Comment by peternied** [comment]
FYI @nibix

**Comment by davidlago** [comment]
Wave 1 seems complete based on the tracked issues above. Closing.
