### ISSUE TITLE
[META] System Indices access for Extensions

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2529]
OpenSearch plugins utilize system indexes to store information that persists through the cluster, such as the security configuration for the Security Plugin or .replication-metadata-store indexes for cross cluster replication. These indexes contain data specific to the plugin and should not be altered by any other plugin or application.

This meta issue is tracking what associated work needs to be done

### Design
- [x] https://github.com/opensearch-project/security/issues/2530
- [x] https://github.com/opensearch-project/OpenSearch/issues/6589 
- [x] Pick a solution
### Implementation
- [x] #2553
- [x] #2845
- [x] #3038
### Questions
- [x] #3259 
### Release
- [x] https://github.com/opensearch-project/documentation-website/issues/4736
### Future Investment
- [ ] #2554

**Comment by peternied** [comment]
`Option 2b: Extension service account, scoped to specific system index [Recommended]` is best aligned based on the current considerations and discussion topic.  I'll add associated work to this meta issue.

**Comment by peternied** [comment]
@opensearch-project/security I've added work items for this META issue, please review the tasks on this item and if we need any more detail.

Small note; I did not create an issue for the documentation because I think we should create the task on the documentation-website by whoever will own that work when its ready.

**Comment by cwperks** [comment]
I wanted to leave an additional comment here. I'm starting not to love the term system indices in this context. IMO System Indices are indices critical for OpenSearch to run. These indices deserve special protection and are critical for an extension to run, but should we keep utilizing the term system index?

I've started calling these reserved indices as the extension would like to _reserve_ these indices for it to store data its needs to function properly. Any thoughts on the naming?

Its important to note that many plugins utilize system index protection provided by the security plugin without explicitly being a system index by `implementing SystemIndexPlugin`.

**Comment by samuelcostae** [comment]
I agree with your point @cwperks , though I lack end user viewpoint what made me agree with you is tha, from a code structure point of view, the issue became much clearer once i considered these "Extension Indicices: as a different category from the already existing "protectedIndices"  listed in the SecurityIndexAccessEvaluator class

**Comment by peternied** [comment]
'System index' is the name of the feature in OpenSearch so we seem pretty locked in.  I'm open to alternative names, when I think of 'extension index' / 'protected index' or something, it would be implemented differently without the relationship to SystemIndexPlugin which is a requirement for backward compatibility with the existing plugins.

**Comment by DarshitChanpura** [comment]
@peternied Can we mark this issue as closed for 2.10?

**Comment by peternied** [comment]
@DarshitChanpura I still see tasks that are incomplete, seems like we shouldn't close it.  What do you think?

**Comment by DarshitChanpura** [comment]
- Is https://github.com/opensearch-project/security/issues/2554 still needed?  
- https://github.com/opensearch-project/documentation-website/issues/4736 is pending PR merge.

**Comment by peternied** [comment]
@DarshitChanpura  thanks for creating the other tracking issue, I'm going to consider this one resolved and we can us that seperate issue for tracking what might be needed for extensions release
