### ISSUE TITLE
[META] On-Behalf-Of Authentication

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#2573]
### Description
When security is installed, extensions will need an auth token in order to interact with the OpenSearch cluster. This auth token will be in the form of a JWT. Extensions are a replacement for plugins, so any information from a user that plugins utilize today should be contained as a claim in the JWT sent to an extension. 

Example header + payload:

```
Header:
{"alg":"HS512"}

Payload:
{
  "iss": "<cluster_name>",
  "iat":1676908684,
  "exp":1676908744,
  "sub":"<principal_identifier_token>",
  "er":"<encrypted_mapped_roles>", # r for roles
  "br": "<encrypted_backend_roles>", # br for backend_roles
  "aud": "extension/{extensionUniqueId}"
}
```

Useful reference class to see how JWTs are generated within the security plugin on successful SAML authentication: https://github.com/opensearch-project/security/blob/main/src/main/java/com/amazon/dlic/auth/http/saml/AuthTokenProcessorHandler.java

For the initial extensions design, these tokens will allow the extension to interact with the OpenSearch cluster using the same privileges as the initiating user. 

For the initial implementation, the JWTs can be signed with an HMAC 512 hash by default. If any encryption is performed, then the extension will require a mechanism for decrypting the JWE to view the payload of the JWT. The signing key should be configured in the security configuration. Maybe in the `config.dynamic` portion of `config.yml`?

### Design
- [x] JWT vs JWE: https://github.com/opensearch-project/security/issues/2545
- [x] https://github.com/opensearch-project/security/pull/2567
- [x] #2620 
- [x] #2619 
    - [x] #2672 
- [x] https://github.com/opensearch-project/security/issues/2615
    - [x] https://github.com/opensearch-project/security/pull/2671
    - [x] https://github.com/opensearch-project/security/pull/2857
- [x] https://github.com/opensearch-project/security/issues/3000
- [x] #2865
- [x] #2764

### Implementation
- [x] https://github.com/opensearch-project/security/pull/3047
- [x] #2891
    - [x] https://github.com/opensearch-project/security/pull/3008
- [x] https://github.com/opensearch-project/security/issues/3102
    - [x] https://github.com/opensearch-project/security/pull/3117
- [x] https://github.com/opensearch-project/security/issues/2707

### Integration
- [x] https://github.com/opensearch-project/security/issues/2945
    - [x] https://github.com/opensearch-project/security/pull/3179
- [x] https://github.com/opensearch-project/security/issues/3176
- [x] https://github.com/opensearch-project/security/issues/2616

### Release Criteria
- [x] #3162
- [ ] https://github.com/opensearch-project/security/issues/3290
- [x] #3267
- [x] https://github.com/opensearch-project/security/issues/2707
- [x] https://github.com/opensearch-project/security/issues/3177
- [x] https://github.com/opensearch-project/security/issues/3101
- [x] #3225
- [x] https://github.com/opensearch-project/security/issues/3558
- [x] #3555 

### Follow-up
- [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/887
  - [ ] https://github.com/opensearch-project/opensearch-sdk-java/pull/892
- [ ] https://github.com/opensearch-project/security/issues/3098
- [x] #3202
- [x] https://github.com/opensearch-project/security/issues/3238

**Comment by cwperks** [comment]
Another useful snippet for this is: [PrivilegesEvaluator#L198-L210](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java#L198-L210(

```
private void setUserInfoInThreadContext(User user, Set<String> mappedRoles) {
    if (threadContext.getTransient(OPENDISTRO_SECURITY_USER_INFO_THREAD_CONTEXT) == null) {
        StringJoiner joiner = new StringJoiner("|");
        joiner.add(user.getName());
        joiner.add(String.join(",", user.getRoles()));
        joiner.add(String.join(",", Sets.union(user.getSecurityRoles(), mappedRoles)));
        String requestedTenant = user.getRequestedTenant();
        if (!Strings.isNullOrEmpty(requestedTenant)) {
            joiner.add(requestedTenant);
        }
        threadContext.putTransient(OPENDISTRO_SECURITY_USER_INFO_THREAD_CONTEXT, joiner.toString());
    }
}
```

This is the information currently read in by common-utils and parsed into the common-utils User object inside of plugins.

**Comment by cwperks** [comment]
`mappedRoles` are:

1. Direct roles mappings of a user to an OpenSearch role

+

2. Backend role resolution - Backend roles resolve to OpenSearch roles via roles_mapping and `mapRoles` is where the resolution takes place

+ 

3. Host resolution - There is a feature in roles_mappings to map requests originating from ip addresses/hostnames to opensearch roles


This function inside of ConfigModel[V6|V7] is where the mapping takes place: [ConfigModelV7#L1206-L1269](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java#L1206-L1269)

**Comment by cwperks** [comment]
Created an issue to track the work to add backend roles to the Create obo token endpoint: https://github.com/opensearch-project/security/issues/2865
