### ISSUE TITLE
[META] Extension Security Management

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#2586]
Extensions are a new concept in OpenSearch and the security plugin needs ways to reference or make decisions about them.  Capturing all of those topics in this meta issue.

#### Application Scopes
- [ ] #2587
- [x] https://github.com/opensearch-project/security/issues/2572
  - Only via OnBehalfOf tokens or ServiceAccount
- [ ] #2644

---
#### Service Accounts
- [x] https://github.com/opensearch-project/security/issues/2584
- [x] https://github.com/opensearch-project/security/issues/2502
- [x] https://github.com/opensearch-project/security/issues/2566
- [x] https://github.com/opensearch-project/security/issues/2552
- [x] https://github.com/opensearch-project/security/issues/2597
