### ISSUE TITLE
Service account design question and issue tracking

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2596]
**This issue tracks all the questions and issues associated with supporting permissions for extensions.**

_NOTE: A checked box means that the linked question has been answered or the linked issue has been resolved._

## Questions: 

- [x] #2526

  - [x] How to determine if a request is destined for an extension?  
    * If a request is destined for an extension the RestHandler will be an instance of RestSendToExtensionAction.

- [x] #2565

    - [x] What syntax should be used?
      * We will keep the existing permission syntax structure.
    - [x] What parsing method should be used?
      * We will use the existing parsing structure with minimal changes to parse the extension permission type.

- [x] #2566
  
  - [x] Where should service account permissions be stored?
    * Service account permissions will be stored with internal users for the time being. 
  - [x]  How should service account permissions be stored?
    * Service account permissions will be stored in the same manner as internal user permissions. 
  - [x] Should roles be used for extension service accounts? 
    * Extension service accounts will make use of role(s). 
  - [x] How should extensions be tracked or managed?
    * Use service accounts: #2594 
  
- [x] #2552

  - [x] How do extensions get starting permissions?
    * Starting permissions are parsed from the extension's configuration file during installation. 
  - [x] How should extensions register ‘predefined’ roles?
    * Custom roles are read from the configuration file during extension installation.
  - [x] How does an admin allow/disallow optional permissions for an extension?
    * There are no optional permissions during an extension's installation process. Additional permissions can be granted by modifying the configuration file or using the internal users API. 
  - [x] How and where does the security plugin enforce extension permissions?
    * Enforce extension permissions after the request leaves the extension and returns to the trust zone

- [x] #2572

  - [x] How can an admin grant and revoke service account permissions?
    * Administrators can change permissions for service accounts using the internal user API.
  - [x] How is an extension prevented from elevating its own permissions?
    * Service accounts will not be able to be granted permissions for calling the internal user update API. 
  - [x] How does DLS/FLS work for extensions?
    * Service accounts and on-behalf-of tokens will support DLF/FLS, scopes/policies will not. 

- [x] #2597 : #2594 

  - [x] How is extension registration tied to service accounts?
    * Extensions request a service account be created for them immediately on registration.
  - [x] How is a service account represented inside of the Security Plugin? 
    * Exactly like a user account except with the attribute "service: true".
  - [x] Is a service account limited/different from normal internal account?
    * For now, service accounts will be treated similarly to user accounts. 
  - [x] How can an extension use its service account?
    * The service account will be what an extension acting on its own behalf is authc/authz'd against. 
  - [x] Can an extension have more than one service account? 
    * For now, service accounts will implicitly be restricted to one per extension since they are tied to the registration process. 
  - [x] How to generate passwords for service accounts and recognize them without storing? 
     * Randomly generate a password and return it to the extension before storing its hash as part of the internal user. 
     
## Issues:

- [x] #2594 
- [x] #2645 
    - [x] Blocked by #2594 
- [x] #2609
- [ ] [Core-side API handling](https://github.com/opensearch-project/OpenSearch/issues/6900)
    - [x] Blocked by #2609
- [x] #2611 
    - [x] Blocked by #2567 
- [x] #2646 
    - [x] Should follow #2611
- [x] #2668 
- [x] #2667 
- [x] #2703 
- [x] [Add Identity to Core](https://github.com/opensearch-project/OpenSearch/pull/7246)

## Flow Diagrams:

- [x] #2666
- [x] #2664
    - [x] The service account is enabled
    - [x] The service account is disabled
- [x] #2665 
    - [x] The service account has the required permissions 
    - [x] The service account does not have the required permissions

**Comment by peternied** [comment]
Thanks for capturing all of the details here, going to use this as a rollup for all of the design, will use https://github.com/opensearch-project/security/issues/2944 for the high level meta tracking
