### ISSUE TITLE
[Extension] Extend the Integration Test Cases of On-Behalf-Of Authentication Backend

### ISSUE THREAD

**Issue by RyanL1997** [opensearch-project/security#2707]
### Description

Extend the Integration Test Cases of On-Behalf-Of Authentication Backend

This testing frame work has been setup in https://github.com/opensearch-project/security/pull/2857 [1]. And lets use this issue to extend the test cases. Here are some of the potential test cases:

- [x] Testing if the create OBO endpoints can be used for issue another OBO Token. (requires - #2891)
- [x] Testing if the create OBO endpoints can be used for modifying auth info, e.g. resetting password. (requires - #2891)
- [ ] Testing of the BWC Mode. (related to #2616 )
- [ ] Test if the create OBO endpoint's incoming request does not get network based role mapped in (related to #3161).

### Required Pull Request

- Authentication Backend: https://github.com/opensearch-project/security/pull/2672
- Extensions config for JWT signing/encryption key: https://github.com/opensearch-project/security/pull/2671

### Reference
[1]: Setup of OBO Authabackend Integration Tests: https://github.com/opensearch-project/security/blob/feature/extensions/src/integrationTest/java/org/opensearch/security/http/OnBehalfOfJwtAuthenticationTest.java
[2]: Similar test cases can be found from `JwtAuthenticationTests.java`: https://github.com/opensearch-project/security/blob/main/src/integrationTest/java/org/opensearch/security/http/JwtAuthenticationTests.java

**Comment by scrawfor99** [comment]
[Triage] This is part of the ongoing Extensions project.

**Comment by RyanL1997** [comment]
This testing frame work has been setup in https://github.com/opensearch-project/security/pull/2857.

**Comment by davidlago** [comment]
Closing, @RyanL1997 please bubble https://github.com/opensearch-project/security/issues/3201 up to the main META
