### ISSUE TITLE
[META] Service Accounts

### ISSUE THREAD

**Issue by scrawfor99** [opensearch-project/security#2944]
This tracking issue describes a feature where applications (plugins/extensions) make use of service accounts when completing actions outside the context of an impersonated user. 

Service Accounts will officially become a context where there is enforcement of permissions and it is possible to determine the context an application is operating under. 

### Design
- [x] https://github.com/opensearch-project/security/issues/2596
- [x] #3200

### Implementation
- [x] #2939
- [x] https://github.com/opensearch-project/security/issues/2704

### Integration
- [x] https://github.com/opensearch-project/security/issues/2611
- [x] https://github.com/opensearch-project/security/issues/2646
- [x] #2942
  - [x] https://github.com/opensearch-project/security/issues/3176
  - [x] https://github.com/opensearch-project/OpenSearch/pull/8526

### Release criteria
- [x] #3201
- [x] #3557 
- [x] https://github.com/opensearch-project/security/issues/3199

### Follow up
- [x] #2941 
- [x] #2943

**Comment by scrawfor99** [comment]
[Triage] This is a tracking issue for work being done in core around Identity.
