### ISSUE TITLE
[META] Admin user should have a custom non-hardcoded password

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/security#3622]
## High-level Idea

As one of the outcome of this [spike](https://github.com/opensearch-project/security/issues/3560), this feature-request is to replace admin password, which is currently hard coded in demo configuration, with a custom password. If none is provided, a random password should be generated and set for admin user. Here is the intended design:

```mermaid
sequenceDiagram
    participant User
    participant Cluster
    participant Script

    User->>Cluster: Start cluster setup with security plugin
    Cluster->>Script: Execute demo script
    alt User provided password
        Script->>Script: Search for user provided password
    else No password provided
        Script->>User: Script execution fails as no password provided
    end
    Script->>Cluster: Continue with demo script execution
    alt Demo script execution successful
        Script->>Cluster: Notify demo script execution complete
    end
    Cluster->>Cluster: Continue with security plugin configuration

```

## Acceptance Criteria

- [x] Update the demo configuration install script to accept a custom password for admin user
~- [ ] If no custom password is provided, the script should generate a new one, set it for admin and let the end user know~ (no longer considered)
- [x] This change works with at-least one of the supported OpenSearch distributions

## Exit Criteria

- [x] #3632
- [x] #3633
- [x] #3636

## Would like

- [x] Implement a password validation logic to ensure that a weak password is not supplied as custom password.

**Comment by scrawfor99** [comment]
[Triage] This is the last of the meta issues tracking progress removing the use of default credentials in the cluster. Marking as triaged given clear action items and exit criteria.

**Comment by DarshitChanpura** [comment]
Closing this as all sub-tasks are now complete.
