### ISSUE TITLE
[Meta] View Experimental Release

### ISSUE THREAD

**Issue by peternied** [opensearch-project/security#3873]
Views is a way to project indices in OpenSearch, these views act as a focal point for describing the underlying data and how the data is accessed.  It allows for restricting the scope and filtering the response consistently.

Resource types are a way to generically describe resources, a new section within the Security Role can express these.

### Tasks
- [ ] Basic View operations in OpenSearch
  - [ ] Add views to the cluster metadata schema 
  - [ ] Search view
  - [ ] Get buy in from OpenSearch maintainers for experimental feature release approval in 2.x
- [ ] Resource type and identifiers in OpenSearch
   - [ ] Resource interfaces
   - [ ] Resource validation patterns
   - [ ] Expose resource type & id mappings to downstream system
- [ ] Resource permission management
   - [ ] Update to the security configuration for new resource section
- [ ] End to end test cases
- [ ] Security Review

### Additional Context
- Design doc
   -  https://github.com/peternied/OpenSearch-1/blob/views/server/src/main/java/org/opensearch/index/view/views-design.md
- Feature Prototype
   - OpenSearch https://github.com/peternied/OpenSearch-1/tree/views
   - Security https://github.com/peternied/security/tree/views

**Comment by scrawfor99** [comment]
[Triage] Going to mark this as triaged since we have a pretty clear path forward and would definitely accept any PRs towards this effort. Thanks @peternied :)
